import type { MetadataRoute } from 'next';

/**
 * Web app manifest — drives "Add to Home Screen" on iOS and Android,
 * and makes Chrome / Safari treat the install as a standalone app.
 *
 * Brand: the touchline pitch green from tailwind config.
 */
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: 'Touchline',
    short_name: 'Touchline',
    description: 'Touch-driven, sport-agnostic live match event tracker.',
    start_url: '/',
    display: 'standalone',
    orientation: 'any',
    background_color: '#0b1220',
    theme_color: '#0b6b3a',
    // Icons are generated by next/og via src/app/icon{,1,2,3}.tsx —
    // see those files for the per-size design.
    icons: [
      {
        src: '/icon1',
        sizes: '192x192',
        type: 'image/png',
        purpose: 'any',
      },
      {
        src: '/icon2',
        sizes: '512x512',
        type: 'image/png',
        purpose: 'any',
      },
      {
        src: '/icon3',
        sizes: '512x512',
        type: 'image/png',
        purpose: 'maskable',
      },
    ],
    categories: ['sports', 'utilities', 'productivity'],
    lang: 'en',
  };
}
